# Generated by Django 4.2.30 on 2026-07-19 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='شرکت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='تلفن')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='سقف اعتبار')),
                ('total_purchases', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='کل خرید')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('customer_type', models.CharField(choices=[('regular', 'عادی'), ('gold', 'طلایی'), ('platinum', 'پلاتینیوم'), ('vip', 'VIP')], default='regular', max_length=20, verbose_name='نوع مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-created_at'],
            },
        ),
    ]
