# Generated by Django 4.2.30 on 2026-07-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_is_potential_customer_last_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='potential_status',
            field=models.CharField(blank=True, choices=[('new_lead', 'سرنخ جدید'), ('initial_intro', 'معرفی اولیه'), ('needs_assessment', 'نیاز سنجی'), ('proposal_sent', 'ارسال پروپزال'), ('follow_up', 'پیگیری'), ('clarification', 'رفع ابهامات'), ('sale', 'فروش'), ('archived', 'بایگانی')], default='new_lead', max_length=20, null=True, verbose_name='وضعیت بالقوه'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, choices=[('google', 'گوگل'), ('telemarketing', 'بازاریابی تلفنی'), ('exhibition', 'نمایشگاه'), ('referral', 'معرفی'), ('social_media', 'شبکه\u200cهای اجتماعی'), ('website', 'وب\u200cسایت'), ('other', 'سایر')], max_length=20, null=True, verbose_name='منبع آشنایی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایر منابع'),
        ),
    ]
