# Generated by Django 4.2.30 on 2026-07-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_potential_status_customer_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customernote',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'یادداشت', 'verbose_name_plural': 'یادداشت\u200cها'},
        ),
        migrations.AddField(
            model_name='customernote',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='پین شده'),
        ),
    ]
