# Generated by Django 4.2.30 on 2026-07-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customernote_options_customernote_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='potential_status_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایر وضعیت\u200cهای بالقوه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='potential_status',
            field=models.CharField(blank=True, choices=[('new_lead', 'سرنخ جدید'), ('initial_intro', 'معرفی اولیه'), ('needs_assessment', 'نیاز سنجی'), ('proposal_sent', 'ارسال پروپزال'), ('follow_up', 'پیگیری'), ('clarification', 'رفع ابهامات'), ('sale', 'فروش'), ('archived', 'بایگانی'), ('other', 'سایر')], default='new_lead', max_length=20, null=True, verbose_name='وضعیت بالقوه'),
        ),
    ]
