# Generated by Django 4.2.30 on 2026-07-20 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0005_customer_potential_status_other_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین مراجعه'),
        ),
        migrations.AddField(
            model_name='customer',
            name='visit_count',
            field=models.IntegerField(default=0, verbose_name='تعداد مراجعه'),
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('bonus_points', models.IntegerField(default=0, verbose_name='امتیاز پاداش')),
                ('bonus_description', models.TextField(blank=True, null=True, verbose_name='توضیحات پاداش')),
                ('min_purchase', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حداقل خرید (تومان)')),
                ('min_visits', models.IntegerField(default=0, verbose_name='حداقل تعداد مراجعه')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'گروه مشتریان',
                'verbose_name_plural': 'گروه\u200cهای مشتریان',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customergroup', verbose_name='گروه مشتریان'),
        ),
    ]
