# Generated by Django 4.2.30 on 2026-07-20 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0006_customer_department_customer_last_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='archive_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل بایگانی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بایگانی'),
        ),
        migrations.AddField(
            model_name='customer',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_customers', to=settings.AUTH_USER_MODEL, verbose_name='بایگانی کننده'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='بایگانی شده'),
        ),
    ]
