# Generated by Django 4.2.30 on 2026-07-21 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ذخیره')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='chat.chatmessage', verbose_name='پیام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام ذخیره شده',
                'verbose_name_plural': 'پیام\u200cهای ذخیره شده',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.CreateModel(
            name='PinnedChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پین')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='chat.chatroom', verbose_name='اتاق چت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_chats', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'چت پین شده',
                'verbose_name_plural': 'چت\u200cهای پین شده',
                'ordering': ['-pinned_at'],
                'unique_together': {('user', 'room')},
            },
        ),
    ]
