# Generated by Django 4.2.30 on 2026-07-21 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_savedmessage_pinnedchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن یادداشت')),
                ('color', models.CharField(choices=[('white', 'سفید'), ('yellow', 'زرد'), ('blue', 'آبی'), ('green', 'سبز'), ('pink', 'صورتی'), ('purple', 'بنفش'), ('red', 'قرمز')], default='white', max_length=20, verbose_name='رنگ')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='پین شده')),
                ('is_archived', models.BooleanField(default=False, verbose_name='بایگانی شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'یادداشت',
                'verbose_name_plural': 'یادداشت\u200cها',
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
    ]
