# Generated by Django 4.2.30 on 2026-07-23 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='ساعت')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='رنگ')),
                ('is_important', models.BooleanField(default=False, verbose_name='مهم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رویداد تقویم',
                'verbose_name_plural': 'رویدادهای تقویم',
                'ordering': ['date', 'time'],
            },
        ),
    ]
