# Generated by Django 4.2.30 on 2026-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_calendarevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='color',
            field=models.CharField(choices=[('blue', 'آبی'), ('green', 'سبز'), ('red', 'قرمز'), ('yellow', 'زرد'), ('purple', 'بنفش'), ('pink', 'صورتی'), ('orange', 'نارنجی')], default='blue', max_length=20, verbose_name='رنگ'),
        ),
    ]
