# Generated by Django 4.2.30 on 2026-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_calendarevent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='priority',
            field=models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'فوری'), ('urgent', 'ضروری')], default='medium', max_length=20, verbose_name='اولویت'),
        ),
    ]
