# Generated by Django 4.2.30 on 2026-07-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قرارداد')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شماره قرارداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/files/', verbose_name='فایل قرارداد')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='contracts/signed/', verbose_name='فایل امضا شده')),
                ('admin_signature', models.TextField(blank=True, null=True, verbose_name='امضای مدیر')),
                ('admin_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضای مدیر')),
                ('employee_signature', models.TextField(blank=True, null=True, verbose_name='امضای کارمند')),
                ('employee_signed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضای کارمند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_admin', 'در انتظار امضای مدیر'), ('pending_employee', 'در انتظار امضای کارمند'), ('signed', 'امضا شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('admin_signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts_as_admin', to=settings.AUTH_USER_MODEL, verbose_name='امضا کننده (مدیر)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
                ('employee_signed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts_as_employee', to=settings.AUTH_USER_MODEL, verbose_name='امضا کننده (کارمند)')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن قرارداد',
                'verbose_name_plural': 'نوتیفیکیشن\u200cهای قرارداد',
                'ordering': ['-created_at'],
            },
        ),
    ]
