# Generated by Django 4.2.30 on 2026-07-23 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_customer_archive_reason_customer_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=50, unique=True, verbose_name='شماره پروژه')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان پروژه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('project_type', models.CharField(choices=[('internal', 'داخلی'), ('external', 'خارجی')], default='internal', max_length=20, verbose_name='نوع پروژه')),
                ('status', models.CharField(choices=[('not_started', 'شروع نشده'), ('in_progress', 'در حال پیشرفت'), ('pending', 'در حال انتظار'), ('cancelled', 'لغو شده'), ('completed', 'تمام شده')], default='not_started', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ اتمام واقعی')),
                ('visibility', models.CharField(choices=[('private', 'فقط خودم'), ('assigned', 'فقط اعضای پروژه'), ('department', 'دپارتمان'), ('public', 'همه')], default='assigned', max_length=20, verbose_name='دسترسی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer', verbose_name='مشتری')),
                ('members', models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='اعضای پروژه')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='projects/files/', verbose_name='فایل')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'فایل پروژه',
                'verbose_name_plural': 'فایل\u200cهای پروژه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نظر پروژه',
                'verbose_name_plural': 'نظرات پروژه',
                'ordering': ['created_at'],
            },
        ),
    ]
