# Generated by Django 4.2.30 on 2026-07-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_departments',
            field=models.CharField(blank=True, help_text='برای انتخاب چند دپارتمان، با کاما جدا کنید', max_length=200, null=True, verbose_name='دپارتمان\u200cهای دسترسی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('private', 'خودم'), ('assigned', 'اعضا'), ('department', 'دپارتمان')], default='assigned', max_length=20, verbose_name='دسترسی'),
        ),
    ]
