# Generated by Django 4.2.30 on 2026-07-23 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0007_customer_archive_reason_customer_archived_at_and_more'),
        ('projects', '0002_project_assigned_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_members',
            field=models.ManyToManyField(blank=True, related_name='project_members', to='customers.customer', verbose_name='مشتریان عضو پروژه'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer', verbose_name='مشتری اصلی'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='اعضای پروژه (کارمندان)'),
        ),
    ]
