# Generated by Django 4.2.30 on 2026-07-20 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='شماره تماس')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff/avatars/', verbose_name='تصویر پروفایل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('hire_date', models.DateField(auto_now_add=True, verbose_name='تاریخ استخدام')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('role', models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیر'), ('sales', 'فروش'), ('support', 'پشتیبانی'), ('warehouse', 'انبارداری'), ('accounting', 'حسابداری'), ('marketing', 'بازاریابی'), ('staff', 'کارمند')], default='staff', max_length=20, verbose_name='نقش')),
                ('can_manage_staff', models.BooleanField(default=False, verbose_name='مدیریت کارکنان')),
                ('can_manage_customers', models.BooleanField(default=False, verbose_name='مدیریت مشتریان')),
                ('can_manage_sales', models.BooleanField(default=False, verbose_name='مدیریت فروش')),
                ('can_manage_warehouse', models.BooleanField(default=False, verbose_name='مدیریت انبار')),
                ('can_manage_accounting', models.BooleanField(default=False, verbose_name='مدیریت حسابداری')),
                ('can_manage_support', models.BooleanField(default=False, verbose_name='مدیریت پشتیبانی')),
                ('can_view_reports', models.BooleanField(default=False, verbose_name='مشاهده گزارشات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارکنان',
                'ordering': ['-created_at'],
            },
        ),
    ]
