# Generated by Django 4.2.30 on 2026-07-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('management', 'مدیریت'), ('sales', 'فروش'), ('marketing', 'بازاریابی'), ('support', 'پشتیبانی'), ('warehouse', 'انبارداری'), ('accounting', 'حسابداری'), ('it', 'فناوری اطلاعات'), ('hr', 'منابع انسانی'), ('other', 'سایر')], default='other', max_length=20, null=True, verbose_name='دپارتمان'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='department_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایر دپارتمان\u200cها'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('manager', 'مدیر'), ('supervisor', 'سرپرست'), ('employee', 'کارمند')], default='employee', max_length=20, verbose_name='نقش'),
        ),
    ]
