# Generated by Django 4.2.30 on 2026-07-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staffprofile_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='role',
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='department',
            field=models.CharField(choices=[('management', 'مدیریت'), ('sales', 'فروش'), ('marketing', 'بازاریابی'), ('support', 'پشتیبانی'), ('warehouse', 'انبارداری'), ('accounting', 'حسابداری'), ('it', 'فناوری اطلاعات'), ('hr', 'منابع انسانی'), ('other', 'سایر')], default='other', max_length=20, verbose_name='دپارتمان'),
        ),
    ]
