# Generated by Django 4.2.30 on 2026-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_staffprofile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='position',
            field=models.CharField(choices=[('ceo', 'مدیرعامل'), ('manager', 'مدیر'), ('supervisor', 'سرپرست'), ('senior', 'کارشناس ارشد'), ('expert', 'کارشناس'), ('junior', 'کارشناس تازه\u200cکار'), ('intern', 'کارآموز'), ('other', 'سایر')], default='expert', max_length=20, verbose_name='سمت'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='position_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='سایر سمت\u200cها'),
        ),
    ]
