# Generated by Django 4.2.30 on 2026-07-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_position_staffprofile_position_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره تماس'),
        ),
    ]
