# Generated by Django 4.2.30 on 2026-07-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staffprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس'),
        ),
    ]
