# Generated by Django 4.2.30 on 2026-07-22 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_public',
        ),
        migrations.AddField(
            model_name='task',
            name='visibility',
            field=models.CharField(choices=[('private', 'فقط من'), ('assigned', 'فقط افراد اختصاص داده شده'), ('department', 'دپارتمان'), ('public', 'همه')], default='assigned', max_length=20, verbose_name='دسترسی'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص به افراد'),
        ),
    ]
